### ISSUE TITLE
Using 35-diskspace, run-parts fails

### ISSUE THREAD

**Issue by sergiofenoll** [yboetz/motd#10]
**System information:** Raspberry Pi 2B running Raspbian 9, fresh install.

After running `sudo run-parts /etc/update-motd.d` containing working scripts and `35-diskspace`, the output looks as follows:

```
### OTHER SCRIPT OUTPUT ###
run-parts: failed to exec /etc/update-motd.d//35-diskspace: Exec format error
run-parts: /etc/update-motd.d//35-diskspace exited with return code 1
```

When runnning 35-diskspace on its own, it generates output and, strangely enough, has exit code 1.
```
sff@raspberrypi:/etc/update-motd.d $ ./35-diskspace

disk usage:
./35-diskspace: line 19: [: : integer expression expected
  /                               4% used out of  32G
  [==================================================]
./35-diskspace: line 19: [: : integer expression expected
  /boot                          51% used out of  46M
  [==================================================]
sff@raspberrypi:/etc/update-motd.d $ echo $?
0
```

Looking at the file itself on line 19, it uses a variable `max_usage` that is never set, maybe it's related to that? Note: I tried setting `max_usage` to 100, just to test it out but that didn't seem to fix the issue.

**Comment by yboetz** [comment]
Can you post the output of

    df -H -x zfs -x squashfs -x tmpfs -x devtmpfs --output=target,pcent,size | tail -n+2

**Comment by sergiofenoll** [comment]
```
sff@raspberrypi:/etc/update-motd.d $ df -H -x zfs -x squashfs -x tmpfs -x devtmpfs --output=target,pcent,size | tail -n+2
/            5%   32G
/boot       51%   46M
```

**Comment by yboetz** [comment]
Did you delete some lines? Because line 19 should be:

     usage=$(echo "$line" | awk '{print $2}' | sed 's/%//')

Nothing with `max_usage` here. If yes, please copy the whole script so I can see on what lines the errors are.

**Comment by sergiofenoll** [comment]
I didn't have the full script, I must not have selected everything when copying it to my machine. Recopied the whole script and now it works as expected.

Sorry for bothering you and thanks for the nice scripts!
