### ISSUE TITLE
36-smartd reports all disks with same temperature.

### ISSUE THREAD

**Issue by HermannBjorgvin** [yboetz/motd#13]
I looked at issue #8 and it looks like this might be the same issue. All my disks are reported to have the same temperature, although it changes occasionally, it's always the same.

I added the relevant lines to my `/etc/smartd.conf` maybe this fixes this also?

Another minor issue I have with the script is it takes 0.8-0.9 seconds to run on my machine. Searching the syslog might be an inefficient way to get the temperature. Caching the output would also work.

I am working on the script now to try to get it to work for me.

**Comment by yboetz** [comment]
In #8 I posted my loglines, you have to check that yours have the same structure. If disks are reported by `/dev/sdX` in your logs then you have to adapt the script.

grepping syslog is quite efficient. One syslog file is ~1.2Mb for me and the script runs in 76ms. It's certainly faster than using hddtemp. Caching would be an option, but not necessary for me. I made sure all scripts run fast enough that I don't need caching. Running all motd files takes around ~450ms on my server, which is acceptable.

**Comment by HermannBjorgvin** [comment]
Ah I see. I'll check my log and try to adapt the script like you said. I'll report back when I get it working.

**Comment by yboetz** [comment]
Btw, I updated the script to use hddtemp instead of grepping syslog.
