### ISSUE TITLE
Doesnt work in debian?

### ISSUE THREAD

**Issue by thepenguinthatwants** [yboetz/motd#14]
Hi!

I am wondering if this needs some dependencies?  I am using debian 9.

I just added this repos file to /etc/update-motd.d/ but nothing seems to have changed.

**Comment by yboetz** [comment]
You have to install `update-motd`, I don't know if debian 9 has it in the repositories. And you also need to  set the `PrintMotd` option to `yes` in your sshd config.

**Comment by thepenguinthatwants** [comment]
Hi!

Thanks for replying. Seems like debian has update-motd and /var/run/motd.dynamic.new has the motd in the way I want it , but for some reasons it doesnt print out when logged in.

Gonna try to check more out.
