### ISSUE TITLE
Use .profile instead update-motd

### ISSUE THREAD

**Issue by e-minguez** [yboetz/motd#2]
Instead using update-motd, you can just modify the ```~/.bash_profile``` to run the scripts at login, adding the script location at the end of the ```~/.bash_profile``` file:

```
~/bin/sysinfo
~/bin/services
~/bin/dockerstatus
~/bin/zpool-bar
...
```

**Comment by yboetz** [comment]
Yes, you can add them to your `.bash_profile` or `.bashrc` files as well. Some of them might not run though, e.g. `30-zpool-*` needs to be run as root.
