### ISSUE TITLE
How to exclude drive paths?

### ISSUE THREAD

**Issue by benjmd** [yboetz/motd#21]
Love the scripts! Is there a way to exclude a directory/path from the disk usage script?
I don't want to show the docker mnts:
/var/lib/docker/aufs/mnt/

I can see that you've done a few locations with the '-x', doesn't appear to work with /var or just var etc. 
Ideally just want to ignore from /var onwards.

Thanks

**Comment by yboetz** [comment]
The `-x` filters filesystems types, but I'm not aware that you can filter directory paths from `df`. So I don't really know how you could do that.

**Comment by eloo** [comment]
you can just add a grep -v after the tail like this
``` 
mapfile -t dfs < <(df -H -x zfs -x squashfs -x tmpfs -x devtmpfs -x overlay --output=target,pcent,size | tail -n+2 | grep -v "/mnt/btr_pool" | grep -v "/boot/efi")
```

**Comment by benjmd** [comment]
Perfect, that did it! Thanks
