### ISSUE TITLE
May need full path to run lolcat

### ISSUE THREAD

**Issue by ThorntonCloud** [yboetz/motd#26]
On my Ubuntu 22.04 install, I had to specify the full path for lolcat to function. Otherwise 10-hostname-color did not display at all on the MOTD.

Full path: /usr/games/lolcat

/usr/bin/env figlet "$(hostname)" | /usr/bin/env lolcat -f

**Comment by yboetz** [comment]
Yes, I had to make the same change on my machine as well at some point.
