### ISSUE TITLE
40-services script doesn't properly detect lxd running from snap

### ISSUE THREAD

**Issue by scottjl** [yboetz/motd#3]
The 40-services script doesn't properly detect lxd when it's running in an Ubuntu snap package. It improperly states the services is inactive. The 60-lxd script, using lxc commands, does properly detect running containers though.

> $ systemctl is-active lxd
> inactive
> $ snap services lxd
> Service     Startup  Current
> lxd.daemon  enabled  active

**Comment by yboetz** [comment]
That is because the `40-services` script only picks up on systemd services. If lxd is installed with snap it runs as a snap service and thus is not detected as a systemd service. You would have to create a separate snap script that goes through active/inactive snap services.

**Comment by beowuff** [comment]
I just edited my 40-services file to check for "snap.lxd.daemon" and "snapd".

However, I think I will be creating a new file for snaps specifically.
