### ISSUE TITLE
36-smartd

### ISSUE THREAD

**Issue by edrose** [yboetz/motd#8]
I can't get your smartd script running on my server, and it seems my smartd logs are a different format to yours. My log lines look like this

`Dec 6 11:21:43 onora smartd[1108]: Device: /dev/sdb [SAT], SMART Usage Attribute: 194 Temperature_Celsius changed from 114 to 113`

(the actual temperature is 34C, I checked with `hddtemp` after seeing that)

They don't contain a UUID like it seems to suggest in the script. Would you be able to post an example of your syslog lines to help me get the script working on my system?

**Comment by yboetz** [comment]
Hi

An example syslog line looks like this:

    Device: /dev/disk/by-uuid/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx [SAT], SMART Usage Attribute: 194 Temperature_Celsius changed from 34 to 33

In my `/etc/smartd.conf` file I have entries for all my disks, e.g.

    /dev/disk/by-uuid/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx -a -d sat -o on -S on -s (S/../.././01|L/../(02|16)/./01) -m root -M exec /usr/share/smartmontools/smartd-runner

I think it would be easy to adapt the script to search for /dev/sd[a-z] instead of UUIDs.

**Comment by edrose** [comment]
Ah yeah, all my disks are being done by /dev/sdX so I just need to change that. Thanks!
